language: java

jdk:
  - oraclejdk8

script: mvn clean compile test package

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Y4ELw65xNmknRCTNcJSy8SnoymA8GT56jNzIER9sO882wTaihsvzMaigsJIhACPpN4hdRsXVFv1nFazY1eHiq2OoX3hhZPbIDfM8Ys4LaKba6T2oS1AEyZbSIL+yZEqpiAKRb6PtoqT117Ay1J3+d4xlH2sTAHkVjJFpnIwjn7T9VaXqHja3ce6YGzXMi9HH2i9Uqzn3J0ZJInTbRvqzcg+E5dgqCTdc8UXG6kg29zkqbNOrx8w0vbHN8r32fzdk729TqAPiIkaLHC8qXk7XD5FISKpPJ9BT4wz+NJah2EYlTtC7JvTOaM3IwAXuEliXbkbc6td+Zj8qQkRGP2yloLQK6qss7i+DRqd1IfCVW0Zl6VEYi8yUQldpmHobAR0EtuU4cr8N1fzw6sGKxdDx1tvBl9/MKTikQ04M3ir/h/TqkitmjvbkljOssTFr2ePYKj+vf3PThNUygbAOHNaewMtygJK62ngIgDohqDfMdZKLaVM4RWedRykJ7pYDO9TwZ00Hzeyr5bGK27PM/wrWBBTY7hL19m9y4Z2F+lSkCDkXqOQS+aDab1FQSIv6qXVzVwgi8x7oJJFyMlMx5G4kxJro8EybztkcqZCOksmJ1CopLwRUohzBsZrq2mk74myVlxlPq34TQoG8cSRXWv5hP/+/edAU4l2fkjNtQR9PUaw="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Anoncheg1/dibd"
      description: "Build submitted via Travis CI"
    notification_email: none
    build_command_prepend: "mvn clean"
    build_command:   "mvn compile"
    branch_pattern: coverity_scan