language: java

jdk:
  - oraclejdk8

script: mvn clean compile test package

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TlKi75Nl7bMaap/wwt4ctYD36niQwdCdYjUcses1Zpom5x5UOSP3s850Dq5b4EQXrujPV7G8JmxLkilX/u3HmZDxmYjQKwJ8jyxHzPfrLL4MtlB8pa2oaTxAYdBV8FfI03jzCls1eM1WrmuggTTXTlXA+F7RLOK25+PRjSaB4YAYRuLEup54q2NDgMrU6U/ehTOob8AQ6ZUAeK/ilkI7CV4Ud3Him560pqjvHy5bnivS0W1dOchhtCbh02Lu0a9Gp3FgMm2XiHvJWF9AV99c7mT18j8XsKm1GEHaA7fnFuWKDwcbQ+oh6VocgGsAAiNZsKdC2M57E0/C+dpHTBdckQLPEv3Ogr6GD6bLZBUqKC+GFweS2QETQNK1sc43BeKl6cguD8db7U9k0IIsfDVKahcA4IOZ/Nm2XDBCDlaBEzIxWlsv7JgOF07TWdqCUVmCBsT/Qh5TuSyK5yjxvTkatyYI5rWYWpiD1ZmBcg7Dv1m6lhLudnRbUV3XhqfPBxefIlPYvSRNMsoO+Ppz15K9beJiSBZsicZ6pwFKSfvalbx3SFjoq9fWHhMSFOSV7/pCgmqFa0ey491r9+5BIPZsqY3WSzIznIolRPmHvoPx88JQ/Zg8WEXKK7zPWTyO3o+bod0DUDoAfxz0uy7UjyAYa4tvZ8O9EUzXy7O0y6jg3L8="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Anoncheg1/dibd"
      description: "Build submitted via Travis CI"
	notification_email: huj21@bk.ru
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
