language: java

jdk:
  - oraclejdk8

script: mvn clean compile test package

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Aoo9lKRkkrASBc1s/FKin3XivGOuWyo0Vu098KkjhCf6xWwoa1wWq1nt6H0TaiUTOak9/MPMGYuBVbMDMiVUVgYMJ0gvn4OT1cAAezxQ9kFZjOc9w6hFxrk4W5Mu8jsFPvFqtqUzV2w95At467mVBbh68bCxIlOyJ/jyZseEOTlhGCWMkt9RYOU3Dby4sHjxQuktnarrgBjWu8ut0/EJ88r+vyJZmE2NtQEE7BKhJiQAF5HWe8xxWJSf64r01+bFtyZA9VkChIW7ZLEWX6WVLih942TufA7fukUx/9XthdL+RjegDzYT8pd4uSrGuWgmRzSVlHmNDBGqwvUQSXvFe5NZmVEKFHAV8e/nT+trUrcoxRA7VxgQKqwy6s7uwVnPKyoh+WyU7+ZHbDD9qEYPXrhT+Tw2YOvVRU8ieGjFpwyLG183Cfgs7QTF6A+6d/pjp9Bgh/D5rtgrw3+/44S5DkdWEZAV2KDNzIa9QG522ff5JjfWSJ9KjrUG+ceOG3LWghPVoRiFwiK47RhvFzjYgeJoEPEvZISTs3tSecTXL7x7tXRBuXwx3ymcOQkTiK1scCsGs6ZM3rSEkzaqtZc8Q6uzUF2U4xsAJmlkEhIMjeZFtFiwo7x2EsT4JBkmT4T/PYz5607GXkEWeZiXpZsZQZmnAcsd97QvPZpb8TGWuFw="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Anoncheg1/dibd"
      description: "Build submitted via Travis CI"
    notification_email: huj21@bk.ru
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan